### PR TITLE
making some changes in css 

### PR DESCRIPTION
**Pull request by khushramnani**

### CODE REVIEW

**Comment by krishvsoni** [comment]
Please share the Screenshot.

**Comment by khushramnani** [comment]
> Please share the Screenshot.



> Please share the Screenshot.

clock

**Comment by krishvsoni** [comment]
Try to change the gradient in the background.

**Comment by khushramnani** [comment]
> Try to change the gradient in the background.

which theme do you want ?
any specific color ?

**Comment by krishvsoni** [comment]
> > Try to change the gradient in the background.
> 
> which theme do you want ? any specific 
For background whatever you select it should match the clock 👾

**Pull request merged**
